# Endpoints
endpoints:
  restart:
    enabled: true

# Eureka
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${eureka.url:http://localhost:8761/eureka}
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${random.int}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

# Hystrix
hystrix:
  threadpool:
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      maximumSize: 30
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1200000

# Logging
logging:
  level:
    com.netflix.discovery: 'ERROR'
    org.springframework.cloud: 'INFO'

# Management
management:
  endpoints:
    web:
      exposure:
        include: '*'
    metrics:
      export:
        prometheus:
          enabled: true
    endpoint:
      metrics:
        enabled: false
      prometheus:
        enabled: true
  security:
    enabled: false
  server:
    servlet:
      context-path: /

# Ribbon
ribbon:
  ReadTimeout: 1200000
  ConnectTimeOut: 1200000
  eureka:
    enabled: true

# Server
server:
  port: ${info.application.port}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types:
      - application/json

zuul:
  ignoredServices: "*"
  routes:
    reclamacao:
      path: /rec-consumidor/**
      serviceId: RECCONSUMIDOR-V1-0-0
      strip-prefix: false
    